/**
 * The slice of the Marketplace API the admin dashboard needs.
 *
 * Generated by hand from /swagger/marketplace/swagger.json — only the category
 * catalogue is used, to supply a real `categoryId` when creating a listing.
 */
export interface CategoryDto {
  id?: string;
  name?: string | null;
  slug?: string | null;
  requiresSize?: boolean;
  parentCategoryId?: string | null;
  iconKey?: string | null;
}
